http:
  services:
    grist:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8484
    dex:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:{{ env "EXT_PORT" }}
    tfa:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:4181
    whoami:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:2222

  middlewares:
    tfa:
      forwardauth:
        address: "http://127.0.0.1:4181"
        authResponseHeaders: "X-Forwarded-User"

  routers:
    route-grist:
      rule: "PathPrefix(`/`)"
      service: grist
      middlewares:
        - tfa
      entryPoints:
        - web
    route-signed-out:
      rule: "PathPrefix(`/signed-out`)"
      service: grist
      entryPoints:
        - web
    route-api:
      rule: "PathPrefix(`/api`)"
      service: grist
      entryPoints:
        - web
    route-assets:
      rule: "PathPrefix(`/v/unknown`)"
      service: grist
      entryPoints:
        - web
    route-dex:
      rule: "PathPrefix(`/dex`)"
      service: dex
      entryPoints:
        - web
    route-who:
      rule: "PathPrefix(`/who`)"
      service: whoami
      entryPoints:
        - web

    https-route-grist:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/`)"
      service: grist
      middlewares:
        - tfa
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    https-route-signed-out:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/signed-out`)"
      service: grist
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    https-route-api:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/api`)"
      service: grist
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    https-route-assets:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/v/unknown`)"
      service: grist
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    https-route-dex:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/dex`)"
      service: dex
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    https-route-who:
      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/who`)"
      service: whoami
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt





#    xmy-router77:
#      rule: "Host(`{{ env "APP_HOST" }}`) && PathPrefix(`/whomeep`)"
#      service: whoami
#      entryPoints:
#        - websecure
#      tls:
#        certResolver: letsencrypt

notmuch: 3
